### ISSUE TITLE
Let's Talk: Energy system

### ISSUE THREAD

**Issue by Boundarybreaker** [CottonMC/cotton#1]
We want to add a standard energy system, but we need to think of how it'll work. We've discussed having a bit more complexity than RF, but no decisions on what that'll entail.

- [ ] Should we have packet or stream-based transfer? (EU vs RF)
- [ ] What "scale" should our system work on? How much energy is one coal worth? How much energy does it take to smelt one item?
- [ ] What downsides should our system have, if any? Loss over distance, overheating, pollution, etc.
- [ ] What should the system be named? What color should it have in UIs?

**Comment by Jacky2611** [comment]
I have thought some more about this topic and think that it would be best if we separate the API from the actual implementations. So that there is one API all mods can build against and different implementations of it.
Users that want something simple can use an energy management mod that behaves more like RF and those that want something more advanced can use a more realistic implementation.

I would probably just start writing a basic system for now to get people to use our api but make sure that all the API related stuff (interfaces) is in a separated Gradle module. This way it will be easier to write other kinds of energy management mods later.

**Comment by Boundarybreaker** [comment]
I don't want to make another RF. RF's over-simplicity led to hyper-inflation, and mods like environmental tech and draconic evolution made things even worse. Vazkii's post [Sins of a Solar Empire](https://vazkii.us/#blog/sins-of-a-solar-empire) explains a lot about my approach to this, and why I want to add in some limitations on how the system works. It doesn't need to be something as infurating or unforgiving as IC2's instant-explosion stuff, but I want to have at least some limitation. I'm really liking the idea of using a packet system, so that there's a hard limit on what speeds stuff can move at, so we don't get the same inflation problem.

**Comment by Jacky2611** [comment]
Yeah, I also don't want something like RF. tbh I really liked ic2 system. It was difficult and challenging but also oh so satisfying if you finally got it working without burning down your house.
I am afraid that a simpler system like RF will soon start to dominate the scene, so making everything energy-related (wires, transformers, pipes,...) independent from tech mods and the api would allow me to simply replace something like RF with another, more challenging, system and still use all the same mods.

**Comment by falkreon** [comment]
closing old issues - any new issues should go in the cotton-energy issue tracker
