### ISSUE TITLE
Allow a global datapack to be enabled by default

### ISSUE THREAD

**Issue by Martmists-GH** [CottonMC/cotton#49]
**Is your feature request related to a problem? Please describe.**
For my modpack, I need to load a custom structure for a mod to work (specifically, ProtoSky). This structure has been added to a custom global datapack through cotton, but is disabled by default, meaning worldgen can't see it.

**Describe the solution you'd like**
Add a config option or pack.mcmeta key that can be used to mark a datapack as loaded by default, or even forcibly loaded.

**Comment by Martmists-GH** [comment]
Looks like this was fixed in c6006d03a1866e8d70e9002ae4991dea038d3d2b, any idea when this will be on CF?

**Comment by 1a2s3d4f1** [comment]
The global datapack function is not work. Must use /reload to reload datapacks
cotton 1.0.6
I do not know why the datapack function not load. The datapack is not disabled.

**Comment by LemmaEOF** [comment]
still not with 1.0.6?

**Comment by 1a2s3d4f1** [comment]
Cotton v1.0.6
Global datapack is different than vanilla datapack. The global datapack can load,but function is not work, I must use /reload command to load function from global datapack.

**Comment by LemmaEOF** [comment]
Oh god, this is gonna be a nightmare for me to fix, isn't it. I'll try and look at this when I have time.

**Comment by lukebemish** [comment]
I can confirm this as a developer for 1.16. My mod needs to dynamically create datapacks during game load, and I was using the global folder. My best guess is the new changes to how datapacks work in 1.16 caused this issue. Maybe a mixin to ResourcePackManager, similar to how fabric-resource-loader works? It might also be worthwhile changing the mixin to inject at the head or at a different method, because currently, in the non-safe-mode case, resourcePackManager.setEnabledProfiles, which you're using for the injection target, is called right before the return, after the datapack set has been assembled, so until the datapacks are reloaded the changes your mixin makes aren't applied.

**Comment by lukebemish** [comment]
Yep, I switched your Inject to use target = "Lnet/minecraft/resource/ResourcePackManager;scanPacks()V" and it seems to work great. I'm not sure what other weird effects this might have, but I didn't notice any obvious crashes or anything.

**Comment by LemmaEOF** [comment]
Ooh, thank you so much! I'll take a look at making this change soon.

**Comment by lukebemish** [comment]
No problem! Hope it doesn't have any weird side effects.

**Comment by LemmaEOF** [comment]
if this doesn't do it I might have to look into adding a fabric api hook for it 🙃
